name: terraform-destroy
on:
  workflow_dispatch:
    inputs:
      destroy_backend:
        description: "Also destroy backend storage (state)?"
        type: choice
        options: ["false", "true"]
        default: "false"

permissions:
  id-token: write
  contents: read

env:
  TF_IN_AUTOMATION: "true"
  ARM_USE_OIDC: "true"

jobs:
  destroy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Azure login (client secret)
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}


      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      # ----- MAIN (with remote backend) -----
      - name: Terraform init (main with backend)
        working-directory: terraform
        run: |
          terraform init \
            -backend-config="resource_group_name=${{ vars.BACKEND_RG }}" \
            -backend-config="storage_account_name=${{ vars.BACKEND_SA }}" \
            -backend-config="container_name=${{ vars.BACKEND_CN }}" \
            -backend-config="key=${{ vars.BACKEND_KEY }}"

      - name: Terraform destroy (main)
        working-directory: terraform
        run: terraform destroy -auto-approve

      # ----- OPTIONAL: destroy backend bootstrap -----
      - name: Terraform init (bootstrap)
        if: ${{ inputs.destroy_backend == 'true' }}
        working-directory: terraform/backend-bootstrap
        run: terraform init

      - name: Terraform destroy (bootstrap)
        if: ${{ inputs.destroy_backend == 'true' }}
        working-directory: terraform/backend-bootstrap
        run: |
          terraform destroy -auto-approve \
            -var "location=${{ vars.TF_LOCATION || 'westeurope' }}" \
            -var "backend_resource_group=${{ vars.BACKEND_RG }}" \
            -var "backend_storage_account=${{ vars.BACKEND_SA }}" \
            -var "backend_container=${{ vars.BACKEND_CN }}" \
            -var "backend_key=${{ vars.BACKEND_KEY }}" \
            -var "sp_client_id=${{ secrets.AZURE_CLIENT_ID }}"
