name: terraform-destroy
on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  TF_IN_AUTOMATION: "true"

jobs:
  destroy:
    runs-on: ubuntu-latest
    env:
      # azurerm provider creds (from your JSON secret)
      ARM_CLIENT_ID:       ${{ fromJSON(secrets.AZURE_CREDENTIALS).clientId }}
      ARM_CLIENT_SECRET:   ${{ fromJSON(secrets.AZURE_CREDENTIALS).clientSecret }}
      ARM_TENANT_ID:       ${{ fromJSON(secrets.AZURE_CREDENTIALS).tenantId }}
      ARM_SUBSCRIPTION_ID: ${{ fromJSON(secrets.AZURE_CREDENTIALS).subscriptionId }}

    steps:
      - uses: actions/checkout@v4

      - name: Azure login (client secret)
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      # 1) Destroy MAIN infra (VM, NIC, NSG, etc.) that uses the remote backend
      - name: Terraform init (main with backend)
        working-directory: terraform
        run: |
          terraform init -input=false -no-color -lock-timeout=5m \
            -backend-config="resource_group_name=${{ vars.BACKEND_RG }}" \
            -backend-config="storage_account_name=${{ vars.BACKEND_SA }}" \
            -backend-config="container_name=${{ vars.BACKEND_CN }}" \
            -backend-config="key=${{ vars.BACKEND_KEY }}"

      - name: Terraform destroy (main)
        working-directory: terraform
        run: |
          terraform destroy -auto-approve -input=false -no-color -lock-timeout=5m \
            -var "location=${{ vars.TF_LOCATION || 'westeurope' }}" \
            -var "vm_admin_username=${{ vars.VM_ADMIN_USERNAME || 'azureuser' }}" \
            -var "ssh_public_key_data=${{ secrets.SSH_PUBLIC_KEY }}"

      # 2) Try to destroy the BACKEND with Terraform (best-effort)
      - name: Terraform init (backend bootstrap)
        working-directory: terraform/backend-bootstrap
        continue-on-error: true
        run: terraform init -input=false -no-color

      - name: Terraform destroy (backend bootstrap)
        working-directory: terraform/backend-bootstrap
        continue-on-error: true
        run: |
          terraform destroy -auto-approve -input=false -no-color -lock-timeout=5m \
            -var "location=${{ vars.TF_LOCATION || 'westeurope' }}" \
            -var "backend_resource_group=${{ vars.BACKEND_RG }}" \
            -var "backend_storage_account=${{ vars.BACKEND_SA }}" \
            -var "backend_container=${{ vars.BACKEND_CN }}" \
            -var "backend_key=${{ vars.BACKEND_KEY }}"

      # 3) Safety net: force-delete the backend RG (handles locks/leftovers)
      - name: Force delete backend resource group (final safeguard)
        run: |
          set -euo pipefail
          RG="${{ vars.BACKEND_RG }}"
          if az group show -n "$RG" >/dev/null 2>&1; then
            echo "Deleting backend RG: $RG"
            az group delete -n "$RG" --yes
            az group wait   -n "$RG" --deleted
            echo "Backend RG $RG deleted."
          else
            echo "Backend RG $RG not found; nothing to delete."
          fi
